language: java
java:
  - 8
services:
  - docker
before_install:
  - composer update
script:
  - docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven:Z -w /usr/src/mymaven maven:3.6-jdk-8 mvn test
